//Dutch SurveyCreator translation 
var dutchSurveyStrings = {
    survey: {
        edit: "Bewerken",
         externalHelpLink: "Kijk en leer hoe u enquêtes maakt",
         externalHelpLinkUrl: "https://www.youtube.com/channel/UCH2ru9okIcooNZfpIbyq4qQ?view_as=subscriber",
         dropQuestion: "Zet hier een vraag uit de Toolbox.",
         addLogicItem: "Maak een regel om de volgorde van de enquête aan te passen.",
         copy: "Kopiëren",
         addToToolbox: "Toevoegen aan toolbox",
         deletePanel: "Paneel verwijderen",
         deleteQuestion: "Vraag verwijderen",
         convertTo: "Converteren naar",
         drag: "Element verslepen",
    },
    //questionTypes
    qt: {
        default: "Standaard",
         checkbox: "Checkbox",
         comment: "Commentaar",
         imagepicker: "Afbeeldingskiezer",
         image: "Afbeelding",
         dropdown: "Keuzemenu",
         file: "Document",
         html: "<Html>",
         matrix: "Matrix (enkele keuze)",
         matrixdropdown: "Matrix (keuzemenu)",
         matrixdynamic: "Matrix (dynamische rijen)",
         multipletext: "Tekst meervoud",
         panel: "Kader",
         paneldynamic: "Kader (dynamische panelen)",
         radiogroup: "Radiogroep",
         rating: "Rating",
         text: "Tekst",
         boolean: "Gesloten vraag",
         expression: "Uitdrukking (alleen-lezen)",
         signaturepad: "Handtekening pad",
         flowpanel: "Flow Kader",
        // added > matrix displayy > Esther
        matrix_column: "Kolom",
        matrix_row: "Rij",
         choices: "keuze",
    },
    //Strings in Editor
    ed: {
        defaultLocale: "Standaard taal",
        survey: "Enquête",
        settings: "Enquête-instellingen",
        settingsTooltip: "Open enquête-instellingen",
        //opjectPropertiesHeader: "Advanced",
        //showObjectProperties: "Show Object Properties",
        //hideObjectProperties: "Hide Object Properties",
        showPanel: "Kader tonen",
        hidePanel: "Kader verbergen",
        //editSurvey: "Edit Survey",
        addNewPage: "Nieuwe pagina toevoegen",
        moveRight: "Scroll naar rechts",
        moveLeft: "Scroll naar links",
        deletePage: "Pagina verwijderen",
        editPage: "Pagina bewerken",
        edit: "Bewerken",
        newPageName: "pagina",
        newQuestionName: "vraag",
        newPanelName: "kader",
        newTextItemName: "tekst",
        testSurvey: "Enquête testen",
        testSurveyAgain: "Test de enquête opnieuw",
        testSurveyWidth: "Breedte enquête:",
        navigToMsg: "Navigeren naar:",
        logic: "Logica enquête",
        embedSurvey: "Enquête integreren",
        translation: "Vertaling",
        saveSurvey: "Enquête opslaan",
        saveSurveyTooltip: "Enquête opslaan",
        designer: "Enquête ontwerpern",
        jsonEditor: "JSON Editor",
        undo: "Ongedaan maken",
        redo: "Opniew",
        undoTooltip: "Laatste wijziging ongedaan maken",
        redoTooltip: "Herhaal de verandering",
        options: "Opties",
        genererenValidJSON: "Genereer geldige JSON",
        generReadableJSON: "Genereer leesbare JSON",
        toolbox: "Toolbox",
        "property-grid": "Eigenschappen",
        toolboxGeneralCategory: "Algemeen",
        //delSelObject: "Delete selected object",
        //editSelObject: "Edit selected object",
        correctJSON: "JSON. korrigeren",
        surveyResults: "Enquête resultaat:",
        surveyResultsTable: "Als tabel",
        surveyResultsJson: "Als JSON",
        resultsTitle: "Titel van vraag",
        resultsName: "Vraag naam",
        resultsValue: "Resultaat",
        resultsDisplayValue: "Waarde weergeven",
        gmodified: "Gewijzigd",
        saving: "Opslaan",
        saved: "Opgeslagen",
        saveError: "Error! Editor-inhoud wordt niet opgeslagen.",
        translationAddLanguage: "Selecteer de te vertalen taal",
        translationShowAllStrings: "Alle tekst weergeven",
        translationShowAllPages: "Toon alle pagina's",
        translationNoStrings: "Geen tekst om te vertalen. Wijzig het filter.",
        translationExportToSCVButton: "Exporteren naar CSV",
        translationImportFromSCVButton: "Importeren vanuit CSV",
        translationMergeLocaleWithDefault: "Samenvoegen met standaard taal",
        bold: "Vet",
        citalic: "Cursief",
        underline: "onderstrepen",
        fpAddQuestion: "Vraag toevoegen ...",
        //completedHtmlOnConditionItemText: "Show if:",
        lg: {
        //Logic tab strings
        page_visibilityName: "Paginazichtbaarheid",
        panel_visibilityName: "Kaderzichtbaarheid",
        panel_enableName: "Kaderinschakelen / uitschakelen",
        question_visibilityName: "Vraagzichtbaarheid",
        question_enableName: "Vraag in- / uitschakelen",
        question_requireName: "Vraag optioneel vereist",
        trigger_completeName: "Enquête invullen",
        trigger_setvalueName: "Stel vraagwaarde in",
        trigger_copyvalueName: "Vraagwaarde kopiëren",
        trigger_skipName: "Ga naar vraag",
        trigger_runExpressionName: "Aangepaste expressie uitvoeren",
        completedHtmlOnConditionName: "Aangepaste 'bedankt pagina' tekst",
        page_visibilityDescription: "Maak de pagina zichtbaar wanneer de logische expressie true retourneert. Houd deze anders onzichtbaar.",
        panel_visibilityDescription: "Maak het paneel zichtbaar wanneer de logische expressie true retourneert. Houd het anders onzichtbaar.",
        panel_enableDescription: "Maak het paneel, en alle elementen erin, ingeschakeld wanneer de logische expressie true retourneert. Houd ze anders uitgeschakeld.",
        question_visibilityDescription: "Maak de vraag zichtbaar wanneer de logische expressie true retourneert. Houd deze anders onzichtbaar.",
        question_enableDescription: "Maak de vraag mogelijk wanneer de logische expressie true retourneert. Houd deze anders uitgeschakeld.",
        question_requireDescription: "Vraag wordt vereist wanneer de logische expressie true retourneert.",
        trigger_completeDescription: "Wanneer de logische expressie waar terugkeert, wordt de enquête voltooid en ziet een eindgebruiker de 'Bedankt pagina'.",
        trigger_setvalueDescription: "Als vraagwaarden, die in de logische expressie worden gebruikt, worden gewijzigd en de logische expressie waar retourneert, wordt de waarde ingesteld op de geselecteerde vraag.",
        trigger_copyvalueDescription: "Als vraagwaarden, die in de logische expressie worden gebruikt, worden gewijzigd en de logische expressie true retourneert, wordt de waarde van een geselecteerde vraag gekopieerd naar een andere geselecteerde vraag.",
        trigger_skipDescription: "Wanneer de logische expressie waar retourneert, slaat de enquête de geselecteerde vraag over of richt deze.",
        trigger_runExpressionDescription: "Wanneer de logische expressie true retourneert, wordt de aangepaste expressie uitgevoerd. U kunt dit expressieresultaat optioneel instellen in de geselecteerde vraag",
        completedHtmlOnConditionDescription: "Als de logische expressie true retourneert, wordt de standaardtekst voor de 'Thank you page' gewijzigd in de opgegeven.",
        itemExpressionText: "Wanneer expressie: '{0}' true retourneert:",
        page_visibilityText: "Maak pagina {0} zichtbaar",
        panel_visibilityText: "Maak paneel {0} zichtbaar",
        panel_enableText: "Paneel {0} inschakelen",
        question_visibilityText: "Maak vraag {0} zichtbaar",
        question_enableText: "Maak vraag {0} inschakelen",
        question_requireText: "Stel vraag {0} verplicht",
        trigger_completeText: "Enquête wordt voltooid",
        trigger_setvalueText: "Stel in vraag: {0} waarde {1}",
        trigger_copyvalueText: "Kopieer naar vraag: {0} waarde van vraag {1}",
        trigger_skipText: "Survey overslaan naar de vraag {0}",
        trigger_runExpressionText1: "Expressie uitvoeren: '{0}'",
        trigger_runExpressionText2: "en stel het resultaat in vraag: {0}",
        voltooidHtmlOnConditionText: "Toon aangepaste tekst voor de bedankpagina.",
        conditions: "Conditie (s)",
        actions: "Actie (s)",
        expressionEditorTitle: "Definieer voorwaarde (n)",
        actionsEditorTitle: "Definieer actie (s)",
        deleteAction: "Actie verwijderen",
        addNewAction: "Nieuwe actie toevoegen",
        selectedActionCaption: "Selecteer een actie om toe te voegen ...",
        expressionInvalid: "De logische expressie is leeg of ongeldig. Corrigeer deze.",
        noActionError: "Voeg tenminste één actie toe.",
        actionInvalid: "Los de problemen in uw actie (s) op.",
        expressionSetup: "",
        actionsSetup: "",

        },
    },
    //Property names in table headers
    // pel: {
    //   isRequired: "Vereist?"
    // },
    //Property Editors
    pe: {
        apply: "Toepassen",
        ok: "OK",
        save: "Oplslaan",
        cancel: "Annuleren",
        reset: "Herstellen",
        refresh: "Vernieuwen",
        close: "Sluiten",
        delete: "Verwijderen",
        add: "Toevoegen",
        addNew: "Nieuw toevoegen",
        addItem: "Item ktoevoegen",
        addOther: "Overige",
        addSelectAll: "Alles selecteren",
        addNone: "Niets",
        removeAll: "Alles verwijderen",
        edit: "Aanpassen",
        back: "Terug",
        saveAndBack: "Opslaan en terug",
        itemValueEdit: "Zichtbaar Ja",
        editChoices: "Opties bewerken",
        showChoices: "Keuzes laten zien",
        move: "verplaatsen",
        empty: "<leeg>",
        notEmpty: "<bewerk waarde>",
        fastEntry: "Snelle invoer",
        formEntry: "Formulier invoeren",
        testService: "Test the service",
        itemSelectorEmpty: "aub element selecteren",
        conditionActionEmpty: "aub aktie selecteren",
        conditionSelectQuestion: "Vraag selecteren...",
        conditionSelectPage: "Pagina selecteren...",
        conditionSelectPanel: "Kader selecteren...",
        conditionValueQuestionTitle: "aub waarde selectern/toevoegen",
        // conditionHelp:
        //   "Please enter a boolean expression. It should return true to keep the question/page visible. For example: {question1} = 'value1' or ({question2} * {question4}  > 20 and {question3} < 5)",
        expressionHelp: "Voer een uitdrukking in. U kunt accolades gebruiken om toegang te krijgen tot de vraagwaarden: '{question1} + {question2}', '({price} * {amount}) * (100 - {discount})' ",
        aceEditorHelp: "Druk op ctrl + spatie om hint voor voltooiing van expressie te krijgen",
        aceEditorRowTitle: "Huidige rij",
        aceEditorPanelTitle: "Huidig kader",
        showMore: "Raadpleeg de documentatie voor meer informatie",
        // conditionShowMoreUrl:
        //   "https://surveyjs.io/Documentation/LibraryParameter?id=Question&parameter=visibleIf",

        assistantTitle: "Beschikbare vragen:",
        cellsEmptyRowsColumns: "Er moet minimaal één kolom of rij zijn",
        propertyIsEmpty: "Voer een waarde in",
        propertyNameIsNotUnique: "Voer een unieke naam in",
        listIsEmpty: "Voeg een nieuw item toe",
        expressionIsEmpty: "Expressie is leeg",
        waarde: "Waarde",
        tekst: "Tekst",
        rowid: "Rij ID",
        imageLink: "afbeelding url",
        columnEdit: "Aanpassen kolom: {0}",
        itemEdit: "Aanpassen item: {0}",
        url: "URL",
        path: "Path",
        valueName: "Naam Waarde",
        titleName: "Titel naam",
        titlePlaceholder: "Titel",
        surveyTitlePlaceholder: "Enquête titel",
        pageTitlePlaceholder: "Pagina titel",
        descriptionPlaceholder: "Omschrijving",
        surveyDescriptionPlaceholder: "Enquête omschrijving",
        pageDescriptionPlaceholder: "Pagina omschrijving",
        hasOther: "Heeft ander item",
        otherText: "Andere itemtekst",
        hasNone: "Heeft geen item",
        noneText: "Geen itemtekst",
        hasSelectAll: "Heeft alles geselecteerd",
        selectAllText: "Selecteer alle itemtekst",
        keuzesMin: "Minimumwaarde voor automatisch gegenereerde items",
        keuzesMax: "Maximale waarde voor automatisch gegenereerde items",
        keuzesStep: "Het verschil tussen automatisch gegenereerde items",
        naam: "naam",
        title: "Titel",
        cellType: "Celtype",
        colCount: "Aantal kolommen",
        keuzesOrder: "Selecteer keuzes volgorde",
        visible: "Is zichtbaar?",
        isRequired: "Is vereist?",
        isAllRowRequired: "Vereist antwoord voor alle rijen",
        requiredErrorText: "Vereiste fouttekst",
        startWithNewLine: "Start met nieuwe regel?",
        rows: "Aantal rijen",
        cols: "Aantal kolommen",
        placeHolder: "Aanduiding",
        showPreview: "Voorbeeld",
        storeDataAsText: "Bewaar JSON als tekst",
        maxSize: "Maximale bestandsgrootte",
        imageHeight: "Afbeeldingshoogte",
        imageWidth: "Afbeeldingsbreedte",
        rowCount: "Aantal rijen",
        columnLayout: "Kolommen layout",
        addRowLocation: "Rijknop locatie toevoegen",
        addRowText: "Knop-tekst: rij toevoegen",
        removeRowText: "Tekst van rijknop verwijderen",
        rateMin: "Minimum tarief",
        rateMax: "Maximaal tarief",
        rateStep: "Rate step",
        minRateDescription: "Beschrijving minimumtarief",
        maxRateDescription: "Maximale tariefbeschrijving",
        inputType: "Invoertype",
        optionsCaption: "Bijschrift opties",
        defaultValue: "Standaardwaarde",
        cellsDefaultRow: "Standaardcelteksten",
        surveyEditorTitle: "Enquête-instellingen bewerken",
        qEditorTitle: "Bewerken: {0}",
        maxLength: "Maximale lengte",
        buildExpression: "Bouwen",
        editExpression: "Bewerken",
        en: "en",
        of: "of",
        remove: "Verwijderen",
        addCondition: "Voorwaarde toevoegen",
        //survey
        showTitle: "Titel weergeven / verbergen",
        locale: "Standaardtaal",
        simulator: "Selecteer apparaat",
        landscapeOrientation: "Landscape",
        mode: "Modus (bewerken / lezen)",
        clearInvisibleValues: "Wis onzichtbare waarden",
        cookieName: "Cookie naam (Uitschakelen dmv enquête tweemaal lokaal uit te voeren)",
        sendResultOnPageNext: "Verzend enquêteresultaten op volgende pagina",
        storeOthersAsComment: "Bewaar waarde 'anderen' in apart veld",
        showPageTitles: "Toon paginatitels",
        showPageNumbers: "Toon paginanummers",
        pagePrevText: "Vorige",
        pageNextText: "Volgende",
        completeText: "Verzenden",
        startSurveyText: "Knop-tekst: start",
        showNavigationButtons: "Toon navigatieknoppen (standaard navigatie)",
        showPrevButton: "Toon knop naar vorige pagina  (gebruiker kan teruggaan naar vorige pagina)",
        firstPageIsStarted: "De eerste pagina in de enquête is een startpagina.",
        showCompletedPage: "Toon voltooide pagina aan het einde (voltooidHtml)",
        goNextPageAutomatic: "Ga bij het beantwoorden van alle vragen automatisch naar de volgende pagina",
        showProgressBar: "Toon voortgangsbalk",
        questionTitleLocation: "Positionering titel van de vraag",
        requiredText: "De vraag vereist symbool (en)",
        questionStartIndex: "Vraagstartindex (1, 2 of 'A', 'a')",
        showQuestionNumbers: "Toon vraagnummers",
        questionTitleTemplate: "Vraagtitelsjabloon, standaard is: '{nee}. {vereisen} {titel}'",
        questionErrorLocation: "Fout in locatie van vraag",
        focusFirstQuestionAutomatic: "Focus op de eerste vraag bij het wijzigen van de pagina",
        questionsOrder: "Volgorde van elementen op de pagina",
        maxTimeToFinish: "Maximale tijd om de enquête te beëindigen",
        maxTimeToFinishPage: "Maximale tijd om een ​​pagina in de enquête te voltooien",
        showTimerPanel: "Show timer kader",
        showTimerPanelMode: "Voorbeeldmodus timerkader",
        renderMode: "Rendermodus",
        allowAddPanel: "Sta toevoeging van een kader toe",
        allowRemovePanel: "Sta kaderverwijdering toe",
        panelAddText: "kadertekst toevoegen",
        panelRemoveText: "Tekst uit kader verwijderen",
        isSinglePage: "Toon alle elementen op één pagina",
        html: "Html",
        expression: "UItdrukking",
        minValue: "Minimumwaarde",
        maxValue: "Maximale waarde",
        minLength: "Minimum lengte",
        maxLength: "Maximale lengte",
        allowDigits: "Cijfers toestaan",
        minCount: "Minimumaantal",
        maxCount: "Maximaal aantal",
        regex: "Reguliere expressie",
        totalText: "Totale tekst",
        totalType: "Totaal type",
        totalExpression: "Total expression",
        totalDisplayStyle: "Totale weergavestijl",
        totalCurrency: "Totale valuta",
        totalFormat: "Totaal formaat",
        // Header  adorner
        logoPosition: "Logo positie",
        addLogo: "Logo toevoegen...",
        changeLogo: "Logo veranderen...",
        logoPositions: {
            none: "Logo verwijderen",
            left: "Links",
            right: "Rechts",
            top: "Bovenaan",
            bottom: "Beneden",
        },
        tabs: {
            general: "Algemeen",
            fileOptions: "Opties",
            html: "Html Editor",
            columns: "Kolommen",
            rows: "Rijen",
            choices: "Opties",
            items: "items",
            visibleIf: "Zichtbaar indien",
            enableIf: "Inschakelen",
            requiredIf: "Nodig indien",
            rateValues: "Beoordeel waarden",
            choicesByUrl: "Webopties",
            matrixChoices: "Standaardopties",
            multipleTextItems: "Tekstinvoer",
            numbering: "Numering",
            validators: "Validators",
            navigation: "Navigatie",
            question: "Vraag",
            completedHtml: "Html voltooid",
            completedHtmlOnCondition: "Html met voorwaarde voltooid",
            loadingHtml: "Laden van HTML",
            timer: "Timer / Quiz",
            calculatedValues: "Calculated Values",
            triggers: "Triggers",
            templateTitle: "Titel van sjabloon",
            totals: "Totaal",
            logic: "Logica",
            layout: "indeling",
            data: "gegevens",
            validation: "Valideren",
            cells: "Cellen",
            showOnCompleted: "Toon kompleet",
            logo: "Logo in enquête Titel",
            others: "Anders",
        },
        editProperty: "Eigenschap bewerken '{0}'",
        editProperty: "Eigenschap bewerken '{0}'",
        items: "[Items: {0}]",
        enterNewValue: "Geef de waarde op.",
        noquestions: "Er staat geen vraag in de enquête.",
        createtrigger: "Maak een trigger",
        keyboardAdornerTip: "Druk op enter-knop om item te bewerken, druk op delete-knop om item te verwijderen, druk op control plus pijl omhoog of pijl omlaag om item te verplaatsen",
        triggerOn: "En",
        triggerMakePagesVisible: "Maak pagina's zichtbaar:",
        triggerMakeQuestionsVisible: "Maak elementen zichtbaar:",
        triggerCompleteText: "Vul de enquête over succes in.",
        triggerNotSet: "De trigger is niet geconfigureerd",
        triggerRunIf: "uitvoeren indien",
        triggerSetToName: "Waarde wijzigen van:",
        triggerFromName: "Kopiër waarde van: ",
        triggerRunExpression: "Voer expressie uit",
        triggerSetValue: "a:",
        triggerGotoName: "Ga naar vraag:",
        triggerIsVariable: "Plaats de variabele niet in het onderzoeksresultaat.",
        triggerRunExpressionEmpty: "aub geldige utdrukking invoeren",
    },
    //Property values
    pv: {
        true: "waar",
        false: "fout",
        inherit: "erven",
        show: "show",
        hide: "verbergen",
        default: "standaard",
        initial: "eerste",
        random: "willekeurig",
        collapsed: "samengevouwen",
        expanded: "uitgevouwen",
        none: "geen",
        fill:"vullen",
        asc: "oplopend",
        desc: "aflopend",
        indeterminate: "onbepaald",
        decimaal: "decimaal",
        currency: "valuta",
        percent: "procent",
        firstExpanded: "Eerst uitgeklapt",
        off: "uit",
        onPanel: "opkader",
        onSurvey: "op enquete",
        list: "lijst",
        progressTop: "boven",
        progressBottom: "beneden",
        progressTopBottom: "beiden",
        horizontaal: "horizontaal",
        vertical: "verticaal",
        top: "boven",
        bottom: "beneden",
        topBottom: "op en neer",
        both: "beiden",
        left: "links",
        color: "kleur",
        date: "datum",
        datetime: "datum en tijd",
        "datetime-local": "dateTime-local",
        email: "email",
        month: "maand",
        number: "nummer",
        password: "wachtwoord",
        range: "range",
        tel: "telefoon",
        text: "tekst",
        time: "tijd",
        url: "url",
        week: "week",
        hidden: "verborgen",
        on: "aan",
        onPage: "op pagina",
        edit: "bewerken",
        display: "lezen",
        onComplete: "Wanneer voltooid",
        onHidden: "als verborgen",
        all: "alles",
        pagina: "pagina",
        survey: "enquête",
        onNextPage: "veranderen pagina",
        onValueChanged: "veranderen waarde",
        //missing > dropdownvalues > added Esther 
        image: "afbeelding",
        contain: "bevatten",
        cover: "bedekken",
        pages: "pagina's",
        page: "pagina",
        questions: "vragen",
        correctQuestions: "goed beantwoorde vragen",
        standard: "standaard",
        singlePage: "enkele pagina",
        questionPerPage: "1 vraag per pagina",
        underInput: "onder antwoord",
        underTitle: "onder titel",
    },
    //Operators
    op: {
        empty: "is leeg",
        notempty: "is niet leeg",
        equal: "gelijk aan",
        notequal: "niet gelijk aan",
        contains: "bevat",
        notcontains: "bevat niet",
        anyof: "enkele",
        allof: "allen",
        greater: "groter",
        less: "kleiner",
        greaterorequal: "groter dan of gelijk aan",
        lessorequal: "kleiner dan of gelijk aan"
    },
    //Embed window
    ew: {
        angular: "Gebruik Angular versie",
        jquery: "Gebruik jQuery-versie",
        knockout: "Gebruik Knockout-versie",
        react: "Gebruik React-versie",
        vue: "Gebruik Vue-versie",
        bootstrap: "Voor bootstrap-omgeving",
        standard: "Geen bootstrap",
        showOnPage: "Toon enquête op één pagina",
        showInWindow: "Toon enquête in een venster",
        loadFromServer: "Laad JSON-enquête van server",
        titleScript: "Scripts en stijlen",
        titleHtml: "HTML",
        titleJavaScript: "JavaScript"
    },
    //Test Survey
    ts: {
        selectPage: "Selecteer test pagina:",
        showInvisibleElements: "Toon onzichtbare elementen",
    },
    validators: {
        answercountvalidator: "aantal antwoorden",
        emailvalidator: "e-mail",
        expressionvalidator: "expression",
        numericvalidator: "numeriek",
        regexvalidator: "regex",
        textvalidator: "tekst"
    },
    triggers: {
        completetrigger: "volledige enquête",
        setvaluetrigger: "aangepaste waarde",
        visibletrigger: "zichtbaarheid wijzigen",
        copyvaluetrigger: "waarde Kopiëren",
        skiptrigger: "ga naar vraag",
        runexpressiontrigger: "expressie uitvoeren",
        visibletrigger: "zichtbaarheid wijzigen"
    },
    //Properties
    p: {
        name: "naam",
        title: {
            name: "titel",
            title: "Leeglaten indien gelijk aan titel"
        },
        page_title: { name: "titel", titel: "Paginatitel" },
        navigationButtonsVisibility: "Zichtbaarheid van navigatieknoppen",
        questionsOrder: "Volgorde van vragen",
        maxTimeToFinish: "Maximale tijd om te eindigen",
        visible: "Zichtbaar",
        visibleIf: "Zichtbaar indien",
        questionTitleLocation: "Locatie titel van vraag",
        description: "Beschrijving",
        state: "Status",
        isRequired: "Is benodigd",
        requiredIf: "nodig indien",
        indent: "Indent",
        requiredErrorText: "Fouttekst",
        startWithNewLine: "Begin met een nieuwe regel",
        innerIndent: "Interne identificatie",
        page: "Pagina",
        width: "Breedte",
        commentText: "Commentaar tekst",
        valueName: "Naam van de waarde",
        enableIf: "Ingeschakeld Ja",
        defaultValue: "Standaardwaarde",
        correctAnswer: "Correct antwoord",
        readOnly: "Alleen lezen",
        validators: "Validators",
        titleLocation: "Locatie titel",
        hasComment: "Heeft commentaar",
        hasOther: "Heeft een ander",
        choices: "Opties",
        choicesOrder: "Volgorde van opties",
        choicesByUrl: "Opties per URL",
        otherText: "Andere tekst",
        otherErrorText: "Fouttekst voor een ander",
        storeOthersAsComment: "Sla anderen op als opmerkingen",
        label: "Label",
        showTitle: "Titel weergeven",
        valueTrue: "Waarde waar",
        valueFalse: "Waarde fout",
        cols: "Kolommen",
        rows: "Rijen",
        placeHolder: "Entry Bookmark",
        optionsCaption: "Titelopties",
        expressie: "Uitdrukking",
        format: "Formaat",
        displayStyle: "Weergavestijl",
        currency: "Valuta",
        useGrouping: "Gebruik groepering",
        showPreview: "Voorbeeld weergeven",
        allowMultiple: "Sta veelvouden toe",
        imageHeight: "Afbeeldingshoogte",
        imageWidth: "Afbeeldingsbreedte",
        storeDataAsText: "Gegevens opslaan als tekst",
        maxSize: "Maximale grootte",
        html: "html",
        columns: "kolommen",
        cells: "cellen",
        isAllRowRequired: "Alle rijen zijn verplicht",
        horizontalScroll: "Horizontaal scrollen",
        cellType: "Celtype",
        columnsLocation: "Locatie kolommen",
        columnColCount: "Aantal kolommen",
        columnMinWidth: "Minimale kolombreedte",
        rowCount: "Aantal rijen",
        minRowCount: "Minimaal aantal rijen",
        maxRowCount: "Maximaal aantal rijen",
        keyName: "Sleutelnaam",
        keyDuplicationError: "Foutbericht voor dubbele sleutel",
        confirmDelete: "Bevestiging verwijderen",
        confirmDeleteText: "Tekst van de te verwijderen bevestiging",
        addRowLocation: "Voeg locatierij toe",
        addRowText: "Rij tekst toevoegen",
        removeRowText: "Tekst uit rij verwijderen",
        items: "items",
        itemSize: "Grootte van het item",
        colCount: "Aantal kolommen",
        templateTitle: "Titel van sjabloon",
        templateDescription: "Sjabloonbeschrijving",
        allowAddPanel: "Sta toe dat kader wordt toegevoegd",
        allowRemovePanel: "Toestaan verwijderen kader",
        panelCount: "Aantal kader",
        minPanelCount: "Minimum aantal kader",
        maxPanelCount: "Maximaal aantal kader",
        panelsState: "Status Kader",
        panelAddText: "Tekst aankadertoevoegen",
        panelRemoveText: "Tekst naar kader verwijderen",
        panelPrevText: "Vorige paneltekst",
        panelNextText: "kader Volgende tekst",
        showQuestionNumbers: "Toon vraagnummers",
        showRangeInProgress: "Toon voortgangsbereik",
        renderMode: "Weergavemodus",
        templateTitleLocation: "Locatie van sjabloontitel",
        rateValues: "Beoordeel waarden",
        rateMin: "Minimum tarief",
        rateMax: "Maximaal tarief",
        rateStep: "Tariefstappen",
        minRateDescription: "Beschrijving minimumtarief",
        maxRateDescription: "Maximale tariefbeschrijving",
        inputType: "Type invoer",
        size: "grootte",
        locale: "taal",
        focusFirstQuestionAutomatic: "Focus eerste automatische vraag",
        completedHtml: "HTML voltooid",
        completedBeforeHtml: "Voltooid vóór HTML",
        loadingHtml: "HTML laden",
        triggers: "Triggers",
        cookieName: "Naam van de cookie",
        sendResultOnPageNext: "Verzend resultaat naar volgende pagina",
        showNavigationButtons: "Toon navigatieknoppen",
        showPrevButton: "Toon vorige knop",
        showPageTitles: "Toon paginatitels",
        showCompletedPage: "Toon pagina voltooid",
        showPageNumbers: "Toon paginanummers",
        questionErrorLocation: "Vraag locatiefout",
        showProgressBar: "Toon voortgangsbalk",
        mode: "Modus",
        goNextPageAutomatic: "Ga naar de volgende automatische pagina",
        checkErrorsMode: "Controleer de foutmodus",
        clearInvisibleValues: "Wis onzichtbare waarden",
        startSurveyText: "Start de enquêtetekst",
        requiredText: "Vereiste tekst",
        questionStartIndex: "Index voor start vraag",
        questionTitleTemplate: "Titel van vraagsjabloon",
        firstPageIsStarted: "De eerste pagina begint",
        isSinglePage: "Het is een enkele pagina",
        maxTimeToFinishPage: "Maximale tijd om de pagina te voltooien",
        showTimerPanel: "Paneltijd weergeven",
        showTimerPanelMode: "Toon kadermodus tijd",
        defaultPanelValue: "Standaard kader waarde",
        defaultRowValue: "Waarde standaard rij",
        hasNone: "heeft geen",
        noneText: "geen tekst",
        text: "tekst",
        //missing; added Esther
        logoWidth: "Logo breedte",
        logoHeight: "Logo Hoogte",
        logoFit:"Logo passen",
        contentMode: "modus",
        imageFit: "Afbeelding passen",
        progressBarType: "Type voortgangsbalk",
        questionsOnPageMode: "Pagina indeling",
        maxTextLength: "Maximale tekst lengte",
        maxOthersLength: "Maximale andere lengte",
        questionDescriptionLocation: "Positionering omschrijving van de vraag",
        questionTitlePattern: "Patroon titel van de vraag",
        calculatedValues: "Waardes berekenen",
        textUpdateMode: "Bijwerken tekst",
        focusOnFirstError: "Focus op eerste fout",
        navigateToUrl: "ga naar url",
        navigateToUrlOnCondition: "ga naar url, onder voorwaarde",
        completedHtmlOnCondition: "voltooid html, onder voorwaarde",
        navigateToUrlOnConditon: "navigeer naar URL op voorwaarde",
        maximumFractionDigits: "Minimaal aantal getallen achther de komma",
        minimumFractionDigits: "Maximaal aantal getallen achther de komma",
        waitForUpload: "Wacht op uplaod",
        useDisplayValuesInTitle: "Gebruik waardes in titel",
        defaultValueFromLastPanel: "Standaard waarde van vorig kader",
        allowAddRows: "Toestaan rijen toevoegen",
        rows: "rij",
        cols: "kolom",
        //additional > Esther
        startSurveyText: "Start",
        otherItemText: "Anders, nl.",
        noneItemText: "Geen",
        selectAllItemText: "Selecteer Alles",
        progressText: "Pagina {0} van {1}",
        panelDynamicProgressText: "Record {0} of {1}",
        questionsProgressText: "Geantwoord {0}/{1} vragen",
        emptySurvey: "Er is geen zichtbare pagina of vraag in deze vragenlijst",
        completingSurvey: "Bedankt voor het invullen van de vragenlijst",
        completingSurveyBefore:
            "Onze gegevens tonen aan dat je deze vragenlijst reeds beantwoord hebt.",
        loadingSurvey: "De vragenlijst is aan het laden...",
        optionsCaption: "Kies...",
        value: "waarde",
        requiredError: "Dit is een vereiste vraag",
        requiredErrorInPanel: "Gelieve ten minste een vraag te beantwoorden.",
        numericError: "Het antwoord moet een getal zijn",
        textMinLength: "Vul minstens {0} karakters in",
        minSelectError: "Selecteer minimum {0} antwoorden",
        maxSelectError: "Selecteer niet meer dan {0} antwoorden",
        textMaxLength: "Gelieve minder dan {0} karakters in te vullen.",
        textMinMaxLength: "Gelieve meer dan {0} en minder dan {1} karakters in te vullen.",
        minRowCountError: "Gelieve ten minste {0} rijen in te vullen.",
        numericMinMax:
            "Uw antwoord '{0}' moet groter of gelijk zijn aan {1} en kleiner of gelijk aan {2}",
        numericMin: "Uw antwoord '{0}' moet groter of gelijk zijn aan {1}",
        numericMax: "Uw antwoord '{0}' moet groter of gelijk zijn aan {1}",
        invalidEmail: "Vul een geldig e-mailadres in",
        invalidExpression: "De uitdrukking: {0} moet 'waar' teruggeven.",
        urlRequestError: "De vraag keerde een fout terug '{0}'. {1}",
        urlGetChoicesError:
            "De vraag gaf een leeg antwoord terug of de 'pad' eigenschap is niet correct",
        exceedMaxSize: "De grootte van het bestand mag niet groter zijn dan {0}",
        otherRequiredError: "Vul het veld 'Anders, nl.' in",
        requiredInAllRowsError: "Deze vraag vereist één antwoord per rij",
        requiredInAllRowsError: "Deze vraag vereist één antwoord per rij",
        uploadingFile:
            "Uw bestand wordt opgeladen. Gelieve enkele seconden te wachten en opnieuw te proberen.",
        loadingFile: "Opladen...",
        chooseFile: "Kies uw bestand(en)...",
        noFileChosen: "Geen bestand gekozen",
        confirmDelete: "Wil je deze gegevens verwijderen?",
        keyDuplicationError: "Deze waarde moet uniek zijn.",
        addColumn: "Voeg kolom toe",
        addRow: "Voeg rij toe",
        removeRow: "Verwijder",
        addPanel: "Nieuwe toevoegen",
        removePanel: "Verwijder",
        choices_Item: "onderwerp",
        matrix_column: "Kolom",
        matrix_row: "Rij",
        savingData: "De resultaten worden bewaard op de server...",
        savingDataError: "Er was een probleem en we konden de resultaten niet bewaren.",
        savingDataSuccess: "De resultaten werden succesvol bewaard!",
        saveAgainButton: "Probeer opnieuw",
        timerMin: "minimum",
        timerSec: "sec",
        timerSpentAll: "U heeft {0} gespendeerd op deze pagina en {1} in totaal.",
        timerSpentPage: "U heeft {0} op deze pagina gespendeerd.",
        timerSpentSurvey: "U heeft in totaal {0} gespendeerd.",
        timerLimitAll:
            "U heeft {0} van {1} op deze pagina gespendeerd en {2} van {3} in totaal.",
        timerLimitPage: "U heeft {0} van {1} gespendeerd op deze pagina.",
        timerLimitSurvey: "U heeft {0} van {1} in het totaal.",
        cleanCaption: "Kuis op",
        clearCaption: "Kuis op",
        chooseFileCaption: "Gekozen bestand",
        removeFileCaption: "Verwijder deze file",
        booleanCheckedLabel: "Ja",
        booleanUncheckedLabel: "Neen",
        confirmRemoveFile: "Bent u zeker dat u deze file wilt verwijderen: {0}?",
        confirmRemoveAllFiles: "Bent u zeker dat u al deze files wilt verwijderen?"
    },
};     
SurveyCreator.localization.locales["nl"] = dutchSurveyStrings;

//current supported languages: en + nl
Survey.surveyLocalization.supportedLocales = ["en","nl"];
//getlanguage settings from current user
//console.log($language);
if (language == "nl"){
    SurveyCreator.localization.currentLocale = "nl";
} else {
    SurveyCreator.localization.currentLocale = "en";
}

var options = {
    showLogicTab: true,
};
//create the SurveyJS Creator and render it in div with id equals to "creatorElement"
var creator = new SurveyCreator.SurveyCreator("creatorElement",options);

//Show toolbox in the right container. It is shown on the left by default
if (typeof surveyjson !== 'undefined') {
    // the variable is defined
    creator.text = JSON.stringify(surveyjson)
}
 
creator.showToolbox = "left";
//Show property grid in the right container, combined with toolbox
creator.showPropertyGrid = "right";
//Make toolbox active by default
creator.rightContainerActiveItem("toolbox");
//Setting this callback will make visible the "Save" button
creator.saveSurveyFunc = function () {
    //save the survey JSON
    $.ajax({
        url: "/mysurvey/surveysave",
        type: "POST",
        data: {surveyjson: creator.text	, surveyname: surveyname, surveypublished_at: surveypublished_at, anonymous: anonymous, no_email: no_email},
        dataType: "json",
        cache: false,
        success:function(data){
            window.location.href = '/mysurvey/surveys';
         }
    });
}